name: InitialDeploy

# When this action will be executed
on:     

  # Allow mannually trigger 
  workflow_dispatch:  
    inputs:
      resourceGroup:
        description: 'Resource Group'
        required: true
        default: 'dapr-workshop'
      location:
        description: 'Location'
        required: true
        default: 'canadacentral'        

jobs:
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get service principal object id
        uses: azure/CLI@v1
        with:
          inlineScript: |
            servicePrincipal=`az ad sp list --query "[? appId=='${{ secrets.AZURE_CREDENTIALS.appId }}']" -o json`
            servicePrincipalObjectId=`echo $servicePrincipal | jq .[0].objectId`
            echo servicePrincipalObjectId=$servicePrincipalObjectId >> $GITHUB_ENV

      - name: Deploy bicep
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create -g ${{ github.event.inputs.resourceGroup }} -l ${{ github.event.inputs.location }}
            az deployment group create -g ${{ github.event.inputs.resourceGroup }} -f ./bicep/main.bicep \
             -p \
                servicePrincipalId=${{ env.servicePrincipalObjectId }}