name: InitialDeploy

# When this action will be executed
on:     

  # Allow mannually trigger 
  workflow_dispatch:  
    inputs:
      resourceGroup:
        description: 'Resource Group'
        required: true
        default: 'dapr-workshop'
      location:
        description: 'Location'
        required: true
        default: 'canadacentral'        

jobs:
 
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Get service principal object id
      #   uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #       clientId=`echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientId`
      #       objectId=`az ad sp show --id $clientId | jq -r .objectId`
      #       echo "objectId=$objectId" >> $GITHUB_ENV

      # - name: Deploy bicep
      #   uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #       az group create -g ${{ github.event.inputs.resourceGroup }} -l ${{ github.event.inputs.location }}
      #       deploymentOutput=`az deployment group create -g ${{ github.event.inputs.resourceGroup }} -f ./master/bicep/main.bicep -p servicePrincipalId=${{ env.objectId }}`
      #       echo keyVaultName=`echo $deploymentOutput  | jq -r .properties.outputs.keyVaultName.value` >> $GITHUB_ENV
      
      #gh secret set KEYVAULT_NAME -b"${{ env.keyVaultName }}"          
      - name: Save Key Vault name
        run: |
          ls -R
          cd master
          gh secret set KEYVAULT_NAME -b"test" 
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}          