name: Simulation

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo     
  push:
    branches:
      - master
    paths:
      - src/Simulation/**      

  # Allow mannually trigger 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: daprworkshopreg.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: ./master/src/Simulation
          push: true
          tags: daprworkshopreg.azurecr.io/simulation:${{ github.sha }}
          file:  ./master/src/Simulation/dockerfile


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}        

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            echo "Starting Deploying"
            az container -n simulation -g dapr-workshop --registry-login-server daprworkshopreg.azurecr.io --registry-username ${{ secrets.REGISTRY_USERNAME }} --registry-password ${{ secrets.REGISTRY_PASSWORD }} --image daprworkshopreg.azurecr.io/simulation:${{ github.sha }} --secure-environment-variables "APPINSIGHTS_INSTRUMENTATIONKEY=${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }} EH_CONNECTIONSTRING=${{ secrets.SERVICEBUS_CONNECTIONSTRING }}" --debug
