name: TrafficControlService

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      - master
    paths:
      - src/TrafficControlService/**
      
  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: daprworkshopreg.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: ./master/src/TrafficControlService
          push: true
          tags: daprworkshopreg.azurecr.io/trafficcontrolservice:${{ github.sha }}
          file: ./master/src/TrafficControlService/dockerfile


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        with:
          path: master

      # - name: Generate revision suffix
      #   run: echo REVISION_SUFFIX=`echo "${{ github.sha }}" | cut -c 1-7` >> $GITHUB_ENV
        
      # - name: Replace tokens in yaml file
      #   uses: cschleiden/replace-tokens@v1
      #   with:
      #     files: '["./master/src/containerapps/trafficcontrolservice.yaml"]'
      #   env: 
      #     registry-server: daprworkshopreg.azurecr.io
      #     registry-username: ${{ secrets.REGISTRY_USERNAME }}
      #     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      #     entrycam-connectionstring: ${{ secrets.ENTRYCAM_CONNECTIONSTRING }}
      #     exitcam-connectionstring: ${{ secrets.EXITCAM_CONNECTIONSTRING }}
      #     servicebus-connectionstring: ${{ secrets.SERVICEBUS_CONNECTIONSTRING }}
      #     storageaccount-name: mldaprworkshopstorage
      #     storageaccount-key: ${{ secrets.STORAGEACCOUNT_KEY }}
      #     image-tag: ${{ github.sha }}
      #     revision-suffix: ${{ env.REVISION_SUFFIX }}
    
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1.0.4
        with:
          azcliversion: 2.29.2
          inlineScript: |
            echo "Installing containerapp extension"
            az provider register --namespace Microsoft.Web
            az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl --yes
            echo "Starting Deploying"
            az containerapp update -n trafficcontrolservice -g dapr-workshop --yaml ./master/src/containerapps/trafficcontrolservice.yaml --debug
