name: VehicleRegistrationService

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo     
  push:
    branches:
      - master
    paths:
      - src/VehicleRegistrationService/**      

  # Allow mannually trigger 
  workflow_dispatch:
    inputs:
      action:
        description: 'Action (create or update)'
        required: true
        default: 'update'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: daprworkshopreg.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: ./master/src/VehicleRegistrationService
          push: true
          tags: daprworkshopreg.azurecr.io/vehicleregistrationservice:${{ github.sha }}
          file:  ./master/src/VehicleRegistrationService/Dockerfile


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Generate revision suffix
        run: echo REVISION_SUFFIX=`echo "${{ github.sha }}" | cut -c 1-7` >> $GITHUB_ENV      
        
      - name: Replace tokens in yaml file
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["./master/src/containerapps/vehicleregistrationservice.yaml"]'
        env: 
          registry-server: daprworkshopreg.azurecr.io
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          image-tag: ${{ github.sha }}          
          revision-suffix: ${{ env.REVISION_SUFFIX }}
    
      - name: Output file
        run: cat ./master/src/containerapps/vehicleregistrationservice.yaml  

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}        

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            echo "Installing containerapp extension"
            az provider register --namespace Microsoft.Web
            az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl --yes
            echo "Starting Deploying"
            az containerapp ${{ github.event.inputs.action }} -n vehicleregistrationservice -g dapr-workshop --yaml ./master/src/containerapps/vehicleregistrationservice.yaml --debug
